name: RC Processor

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:
  
jobs:
    create-tag:
        if: github.event.created != true
        runs-on: ubuntu-latest
        steps:
            - name: Print
              run: echo "Triggering build when release branch is. Event name is" ${{ github.event_name }}