name: RC Processor

on:
  push:
    branches:
      - 'release/**'

jobs:
    create-tag:
        if: github.event.created
        runs-on: ubuntu-latest
        steps:
            - name: Print
              run: echo "Triggering build when release branch is"