name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Hotfix
      rc_number:
        description: 'Release candidate number'
        required: true
        default: '1'
        type: choice
        options:
        - 1
        - 2
        - 3
        - 4 
        - 5
        - 6
        - 7
        - 8
        - 9 
        - 10
      should_create_tag:
        description: "Should create and push git tag"
        required: true
        default: true
        type: boolean
      should_trigger_deploy_qa:
        description: "Should trigger `Deploy QA` job"
        required: true
        default: true
        type: boolean
jobs:
    create-tag:
        runs-on: ubuntu-latest
        steps:
          - run: |
              echo "RELEASE_TYPE: $RELEASE_TYPE"
              echo "RC_NUMBER: $RC_NUMBER"
              echo "SHOULD_TAG: $SHOULD_TAG"
              echo "SHOULD_DEPLOY: $SHOULD_DEPLOY"
            env:
              RELEASE_TYPE: ${{ inputs.release_type }}
              RC_NUMBER: ${{ inputs.rc_number }}
              SHOULD_TAG: ${{ inputs.should_create_tag }}
              SHOULD_DEPLOY: ${{ inputs.should_trigger_deploy_qa }}