name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Hotfix
      rc_number:
        description: 'Release candidate number'
        required: true
        default: '1'
        type: choice
        options: # Can be extended later if needed
        - 1
        - 2
        - 3
        - 4 
        - 5
        - 6
        - 7
        - 8
        - 9 
        - 10
      should_create_tag:
        description: "Should create and push git tag"
        required: true
        default: true
        type: boolean
      should_trigger_deploy_qa:
        description: "Should trigger `Deploy QA` job"
        required: true
        default: true
        type: boolean
jobs:
    create-tag:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - uses: actions/checkout@v4
          - run: |
              branch_name=release/${{ inputs.rc_number }}
              echo "Branch name is: $branch_name"
              echo "Hello from old flow"