name: RC Processor

on:
  push:
    branches:
      - 'release/**'

jobs:
    do-something:
        runs-on: ubuntu-latest
        steps:
            - name: Print
              run: echo "Event name: ${{ github.event_name }}"
        