name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - hotfix
      rc_number:
        description: 'Release candidate number'
        required: true
        default: '1'
        type: choice
        options:
        - 1
        - 2
        - 3
        - 4 
        - 5
        - 6
        - 7
        - 8
        - 9 
        - 10
      skip_tagging:
        description: 'Should skip creating and pushin a git tag'
        required: true
        default: false
        type: boolean
      skip_deploy_qa:
        description: 'Should skip triggering `Deploy QA' job
        required: true
        default: false
        type: boolean
jobs:
    create-tag:
        if: github.event.created != true
        runs-on: ubuntu-latest
        steps:
            - name: Print
              run: echo "Triggering build when release branch is. Event name is" ${{ github.event_name }}